# The name of the workflow
name: Test Project
# What triggers the workflow.
# See these events: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows 
on: workflow_dispatch
# A list of jobs
jobs: 
# This is the first named job.
  first-job:
  # What environment to use. See this link for more details and a list of supported runners:
  # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#overview-of-github-hosted-runners 
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting 
        run: echo "hello world"
        # use with: when configuration is needed
      - name: Print goodbye
        run: echo "goodbye!"
        # It's possible to run multi-line entries in a single step as such (note indenting):
        #run: |
        #  echo "first step"
        #  echo "second step"